In [1]:
import utils
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

%matplotlib inline

In [2]:
train_loader, test_loader = utils.mnist()

In [3]:
batch_x, batch_y = next(iter(train_loader))
print(batch_x.shape, batch_y.shape)

torch.Size([50, 1, 28, 28]) torch.Size([50])


In [4]:
flatten_x = batch_x.view(-1, 784)
print(flatten_x.shape)

torch.Size([50, 784])


In [5]:
layer = nn.Linear(784, 10)
print([p.shape for p in layer.parameters()])
params = [p for p in layer.parameters()]
print(params[1])

[torch.Size([10, 784]), torch.Size([10])]
Parameter containing:
tensor([ 0.0155, -0.0199, -0.0298,  0.0313,  0.0083, -0.0049,  0.0018, -0.0265,
        -0.0318, -0.0150], requires_grad=True)


In [6]:
hidden_x = layer(flatten_x)
print(hidden_x.shape, hidden_x[0][:10])

torch.Size([50, 10]) tensor([-0.4147,  0.5613, -0.3931,  0.1447, -0.9887,  0.0196,  0.1484, -0.5025,
        -0.4699, -0.0194], grad_fn=<SliceBackward0>)


In [7]:
rectified = F.relu(hidden_x)
print(hidden_x[0])
print(rectified[0])

tensor([-0.4147,  0.5613, -0.3931,  0.1447, -0.9887,  0.0196,  0.1484, -0.5025,
        -0.4699, -0.0194], grad_fn=<SelectBackward0>)
tensor([0.0000, 0.5613, 0.0000, 0.1447, 0.0000, 0.0196, 0.1484, 0.0000, 0.0000,
        0.0000], grad_fn=<SelectBackward0>)
